/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthenticatedRouteImport } from './app/routes/_authenticated'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthenticatedSettingsRouteImport } from './app/routes/_authenticated/settings'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './app/routes/_authenticated/applications.index'
import { Route as AuthenticatedProcessesIndexRouteImport } from './app/routes/_authenticated/processes.index'
import { Route as AuthenticatedProcessesKeyRouteImport } from './app/routes/_authenticated/processes.$key'
import { Route as AuthenticatedTasksIndexRouteImport } from './app/routes/_authenticated/tasks.index'
import { Route as AuthenticatedTasksStartRouteImport } from './app/routes/_authenticated/tasks.start'
import { Route as AuthenticatedApplicationsAppKeyIndexRouteImport } from './app/routes/_authenticated/applications.$appKey.index'
import { Route as AuthenticatedProcessesInstancesIndexRouteImport } from './app/routes/_authenticated/processes.instances.index'
import { Route as AuthenticatedProcessesInstancesIdRouteImport } from './app/routes/_authenticated/processes.instances.$id'
import { Route as AuthenticatedApplicationsAppKeyFilesFileKeyRouteImport } from './app/routes/_authenticated/applications.$appKey.files.$fileKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessesIndexRoute =
  AuthenticatedProcessesIndexRouteImport.update({
    id: '/processes/',
    path: '/processes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessesKeyRoute =
  AuthenticatedProcessesKeyRouteImport.update({
    id: '/processes/$key',
    path: '/processes/$key',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksStartRoute = AuthenticatedTasksStartRouteImport.update({
  id: '/tasks/start',
  path: '/tasks/start',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsAppKeyIndexRoute =
  AuthenticatedApplicationsAppKeyIndexRouteImport.update({
    id: '/applications/$appKey/',
    path: '/applications/$appKey/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessesInstancesIndexRoute =
  AuthenticatedProcessesInstancesIndexRouteImport.update({
    id: '/processes/instances/',
    path: '/processes/instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessesInstancesIdRoute =
  AuthenticatedProcessesInstancesIdRouteImport.update({
    id: '/processes/instances/$id',
    path: '/processes/instances/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsAppKeyFilesFileKeyRoute =
  AuthenticatedApplicationsAppKeyFilesFileKeyRouteImport.update({
    id: '/applications/$appKey/files/$fileKey',
    path: '/applications/$appKey/files/$fileKey',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/processes/$key': typeof AuthenticatedProcessesKeyRoute
  '/tasks/start': typeof AuthenticatedTasksStartRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/processes/': typeof AuthenticatedProcessesIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/processes/instances/$id': typeof AuthenticatedProcessesInstancesIdRoute
  '/applications/$appKey/': typeof AuthenticatedApplicationsAppKeyIndexRoute
  '/processes/instances/': typeof AuthenticatedProcessesInstancesIndexRoute
  '/applications/$appKey/files/$fileKey': typeof AuthenticatedApplicationsAppKeyFilesFileKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/processes/$key': typeof AuthenticatedProcessesKeyRoute
  '/tasks/start': typeof AuthenticatedTasksStartRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/processes': typeof AuthenticatedProcessesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/processes/instances/$id': typeof AuthenticatedProcessesInstancesIdRoute
  '/applications/$appKey': typeof AuthenticatedApplicationsAppKeyIndexRoute
  '/processes/instances': typeof AuthenticatedProcessesInstancesIndexRoute
  '/applications/$appKey/files/$fileKey': typeof AuthenticatedApplicationsAppKeyFilesFileKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/processes/$key': typeof AuthenticatedProcessesKeyRoute
  '/_authenticated/tasks/start': typeof AuthenticatedTasksStartRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/processes/': typeof AuthenticatedProcessesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/processes/instances/$id': typeof AuthenticatedProcessesInstancesIdRoute
  '/_authenticated/applications/$appKey/': typeof AuthenticatedApplicationsAppKeyIndexRoute
  '/_authenticated/processes/instances/': typeof AuthenticatedProcessesInstancesIndexRoute
  '/_authenticated/applications/$appKey/files/$fileKey': typeof AuthenticatedApplicationsAppKeyFilesFileKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/processes/$key'
    | '/tasks/start'
    | '/applications/'
    | '/processes/'
    | '/tasks/'
    | '/processes/instances/$id'
    | '/applications/$appKey/'
    | '/processes/instances/'
    | '/applications/$appKey/files/$fileKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/processes/$key'
    | '/tasks/start'
    | '/applications'
    | '/processes'
    | '/tasks'
    | '/processes/instances/$id'
    | '/applications/$appKey'
    | '/processes/instances'
    | '/applications/$appKey/files/$fileKey'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/processes/$key'
    | '/_authenticated/tasks/start'
    | '/_authenticated/applications/'
    | '/_authenticated/processes/'
    | '/_authenticated/tasks/'
    | '/_authenticated/processes/instances/$id'
    | '/_authenticated/applications/$appKey/'
    | '/_authenticated/processes/instances/'
    | '/_authenticated/applications/$appKey/files/$fileKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processes/': {
      id: '/_authenticated/processes/'
      path: '/processes'
      fullPath: '/processes/'
      preLoaderRoute: typeof AuthenticatedProcessesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processes/$key': {
      id: '/_authenticated/processes/$key'
      path: '/processes/$key'
      fullPath: '/processes/$key'
      preLoaderRoute: typeof AuthenticatedProcessesKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/start': {
      id: '/_authenticated/tasks/start'
      path: '/tasks/start'
      fullPath: '/tasks/start'
      preLoaderRoute: typeof AuthenticatedTasksStartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$appKey/': {
      id: '/_authenticated/applications/$appKey/'
      path: '/applications/$appKey'
      fullPath: '/applications/$appKey/'
      preLoaderRoute: typeof AuthenticatedApplicationsAppKeyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processes/instances/': {
      id: '/_authenticated/processes/instances/'
      path: '/processes/instances'
      fullPath: '/processes/instances/'
      preLoaderRoute: typeof AuthenticatedProcessesInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processes/instances/$id': {
      id: '/_authenticated/processes/instances/$id'
      path: '/processes/instances/$id'
      fullPath: '/processes/instances/$id'
      preLoaderRoute: typeof AuthenticatedProcessesInstancesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$appKey/files/$fileKey': {
      id: '/_authenticated/applications/$appKey/files/$fileKey'
      path: '/applications/$appKey/files/$fileKey'
      fullPath: '/applications/$appKey/files/$fileKey'
      preLoaderRoute: typeof AuthenticatedApplicationsAppKeyFilesFileKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProcessesKeyRoute: typeof AuthenticatedProcessesKeyRoute
  AuthenticatedTasksStartRoute: typeof AuthenticatedTasksStartRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedProcessesIndexRoute: typeof AuthenticatedProcessesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedProcessesInstancesIdRoute: typeof AuthenticatedProcessesInstancesIdRoute
  AuthenticatedApplicationsAppKeyIndexRoute: typeof AuthenticatedApplicationsAppKeyIndexRoute
  AuthenticatedProcessesInstancesIndexRoute: typeof AuthenticatedProcessesInstancesIndexRoute
  AuthenticatedApplicationsAppKeyFilesFileKeyRoute: typeof AuthenticatedApplicationsAppKeyFilesFileKeyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProcessesKeyRoute: AuthenticatedProcessesKeyRoute,
  AuthenticatedTasksStartRoute: AuthenticatedTasksStartRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedProcessesIndexRoute: AuthenticatedProcessesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedProcessesInstancesIdRoute:
    AuthenticatedProcessesInstancesIdRoute,
  AuthenticatedApplicationsAppKeyIndexRoute:
    AuthenticatedApplicationsAppKeyIndexRoute,
  AuthenticatedProcessesInstancesIndexRoute:
    AuthenticatedProcessesInstancesIndexRoute,
  AuthenticatedApplicationsAppKeyFilesFileKeyRoute:
    AuthenticatedApplicationsAppKeyFilesFileKeyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
